### ISSUE TITLE
FileContent: is it expected tothrow?

### ISSUE THREAD

**Issue by shamdor** [elenakhas/teachers-editor#15]
https://github.com/elenakhas/teachers-editor/blob/10d6952f73f1e01a37c99c5b7268a56ab7cb2800/src/main/java/document/FileContent.java#L19

You say it throws in a comment, but actually catch the exception and so not let it be thrown outside. 
You have to understand which behavior you want(talk to the guru) and fix either the code or the comment

**Comment by shamdor** [comment]
Also a good idea to apply the same strategy in VocabularyLoader

**Comment by elenakhas** [comment]
Comment is automatically generated by the IDE, and everything that does file treatment throws IOexception. As far as I understand...

**Comment by shamdor** [comment]
Well, Files.readAllBytes does throw, but you catch(line 35) it and therefor your method does not throw.
